CREATE TABLE IF NOT EXISTS usermail (id SERIAL PRIMARY KEY, mail VARCHAR(150) UNIQUE NOT NULL);

CREATE TABLE IF NOT EXISTS manga (id SERIAL PRIMARY KEY, title VARCHAR(150) UNIQUE NOT NULL, image VARCHAR(150) NOT NULL);
CREATE TABLE IF NOT EXISTS usermail_manga (
usermail_id INT REFERENCES usermail (id) ON DELETE CASCADE, 
manga_id INT REFERENCES manga (id) ON DELETE CASCADE,
CONSTRAINT usermail_manga_id PRIMARY KEY (usermail_id, manga_id)
);